backend:
  name: github
  repo: docbnmu/docbnmu-website

publish_mode: editorial_workflow
media_folder: static/documents
public_folder: /documents
logo_url: https://docbnmu.in/banner.png
collections:
  - name: "notice"
    label: "Notice"
    folder: "content/notices"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    